### ISSUE TITLE
Getting "Could not open output writer: <C:\Case_4_Schema_Combined.html>: C:\Case_4_Schema_Combined.html" even after having graphviz setup in system

### ISSUE THREAD

**Issue by prarthona21** [schemacrawler/SchemaCrawler#1027]
### Description

**Command**: schemacrawler --server=db2 --host= ** --database=*** --port=50001 --user=*** --password=*** --schemas=*** --info-level=standard --command=brief --tables=".*\.Table Name.*" --only-matching --table-types=TABLE --output-format=html --output-file=C:\Case_4_Schema_Combined.html --log-level=CONFIG

**Log**:
CONFIG: {
  "@object": "schemacrawler.tools.command.text.schema.options.SchemaTextOptions",
  "colorMap": "{.*.FOR_LINT=#EEEEEE}",
  "hideNames":   {
    "hideAlternateKeyNames": false,
    "hideForeignKeyNames": false,
    "hideIndexNames": false,
    "hidePrimaryKeyNames": false,
    "hideRoutineSpecificNames": false,
    "hideTableConstraintNames": false,
    "hideTriggerNames": false,
    "hideWeakAssociationNames": false
  },
  "identifierQuotingStrategy": "quote_if_special_characters_and_reserved_words",
  "isAlphabeticalSortForForeignKeys": false,
  "isAlphabeticalSortForIndexes": false,
  "isAlphabeticalSortForRoutineParameters": false,
  "isAlphabeticalSortForRoutines": false,
  "isAlphabeticalSortForTableColumns": false,
  "isAlphabeticalSortForTables": true,
  "isHideRemarks": false,
  "isHideTableRowCounts": false,
  "isNoSchemaColors": false,
  "isNoSchemaCrawlerInfo": false,
  "isShowDatabaseInfo": false,
  "isShowJdbcDriverInfo": false,
  "isShowOrdinalNumbers": false,
  "isShowStandardColumnTypeNames": false,
  "isShowUnqualifiedNames": false
}
Feb 15, 2023 2:11:48 PM schemacrawler.tools.commandline.utility.CommandLineLogger logState
INFO: Environment:
  SchemaCrawler 16.19.7
  Windows 10 10.0
  Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_202-b08
  DB2/LINUXX8664 SQL110580
  IBM Data Server Driver for JDBC and SQLJ 4.32.28

Feb 15, 2023 2:11:48 PM schemacrawler.tools.commandline.utility.CommandLineLogger logSafeArguments
INFO: Command line:
--server=db2
--host=******
--database=*****
--port=50001
--user=****
<password provided>
--schemas=****
--info-level=standard
--command=brief
--tables=.*\.table name.*
--only-matching
--table-types=TABLE
--output-format=html
--output-file=C:\Case_4_Schema_Combined.html
--log-level=CONFIG
Feb 15, 2023 2:11:48 PM schemacrawler.tools.commandline.utility.CommandLineLogger logFatalStackTrace
SEVERE: Cannot execute SchemaCrawler command
picocli.CommandLine$ExecutionException: Cannot execute SchemaCrawler command
        at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:113)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.executeCommandLine(SchemaCrawlerCommandLine.java:110)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:72)
        at schemacrawler.Main.main(Main.java:76)
Caused by: schemacrawler.schemacrawler.exceptions.IORuntimeException: Could not open output writer: <C:\Case_4_Schema_Combined.html>: C:\Case_4_Schema_Combined.html
        at schemacrawler.tools.options.OutputOptions.openNewOutputWriter(OutputOptions.java:139)
        at schemacrawler.tools.text.formatter.base.BaseFormatter.<init>(BaseFormatter.java:83)
        at schemacrawler.tools.text.formatter.base.BaseTabularFormatter.<init>(BaseTabularFormatter.java:56)
        at schemacrawler.tools.text.formatter.schema.SchemaTextFormatter.<init>(SchemaTextFormatter.java:112)
        at schemacrawler.tools.command.text.schema.SchemaTextRenderer.getSchemaTraversalHandler(SchemaTextRenderer.java:94)
        at schemacrawler.tools.command.text.schema.SchemaTextRenderer.execute(SchemaTextRenderer.java:56)
        at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:116)
        at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:110)
        ... 3 more
Caused by: java.nio.file.AccessDeniedException: C:\Case_4_Schema_Combined.html
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.nio.file.Files.newOutputStream(Unknown Source)
        at java.nio.file.Files.newBufferedWriter(Unknown Source)
        at us.fatehi.utility.ioresource.FileOutputResource.openNewOutputWriter(FileOutputResource.java:72)
        at schemacrawler.tools.options.OutputOptions.openNewOutputWriter(OutputOptions.java:136)
        ... 10 more

SchemaCrawler 16.19.7

Error: Could not open output writer: <C:\Case_4_Schema_Combined.html>: C:\Case_4_Schema_Combined.html

Run SchemaCrawler again with just the
-h
option for help

Or, run SchemaCrawler again with an additional
--log-level=CONFIG
option for details on the error

Additional resources are on the SchemaCrawler website,
https://www.schemacrawler.com
and a live, interactive tutorial is on
https://killercoda.com/schemacrawler

Environment:
  SchemaCrawler 16.19.7
  Windows 10 10.0
  Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_202-b08
  DB2/LINUXX8664 SQL110580
  IBM Data Server Driver for JDBC and SQLJ 4.32.28

Feb 15, 2023 2:11:48 PM schemacrawler.tools.commandline.state.ShellState disconnect
INFO: Closing database connections

**Schemacrawler version 16.19.7 and graphiviz 7.0.1**

### How to Reproduce

Mentioned above(command)

### Relevant log output

Mentioned above
### SchemaCrawler Version

16.19.7

### Java Version

8

### Operating System and Version

OS Name	Microsoft Windows 11 Enterprise and Version 10.0.22000 Build 22000

### Relational Database System and Version

Dbeaver 22.2.3

### JDBC Driver and Version

NA

**Comment by prarthona21** [comment]
Resolved it using a another directory but even though its storing only schema details not diagram. Could you please help on this?

**Comment by prarthona21** [comment]
> Resolved it using a another directory but even though its storing only schema details not diagram. Could you please help on this?

Issue resolved when I downgraded schemaCrawler version to 16.16.16

**Comment by sualeh** [comment]
Please could you send me the full log of
