### ISSUE TITLE
Upgrading from version 16.22.3 to 16.23.2 reports errors：java.io.IOException: Cannot read classpath resource, </postgresql.information_schema/ADDITIONAL_COLUMN_ATTRIBUTES.sql>

### ISSUE THREAD

**Issue by lakxtxue** [schemacrawler/SchemaCrawler#1788]
### Description

向您表达由衷的谢意，贡献如此出色的库：
我在 windows 下使用 idea 开发，采用 springboot 3.4 和 schemacrawler-postgresql 开发我的 web 应用。
今天我在升级之后，启动程序后看到这些错误日志。但是我看到输出为 警告级别，所以这可能是预期的吗？
我不知道会带来什么影响，目前已经回退到 16.22.3 版本，可以正常使用。

### How to Reproduce

`final LimitOptionsBuilder limitOptionsBuilder = LimitOptionsBuilder.builder()
                .includeSchemas(Objects.equals("*",schemaExpr)?new IncludeAll():new RegularExpressionInclusionRule(schemaExpr))
                .includeTables(Objects.equals("*",tableExpr)?new IncludeAll():new RegularExpressionInclusionRule(tableExpr));

        final LoadOptionsBuilder loadOptionsBuilder = LoadOptionsBuilder.builder()
                .withSchemaInfoLevel(SchemaInfoLevelBuilder.standard());
        final SchemaCrawlerOptions options = SchemaCrawlerOptionsBuilder.newSchemaCrawlerOptions()
                .withLimitOptions(limitOptionsBuilder.toOptions())
                .withLoadOptions(loadOptionsBuilder.toOptions());
        final DatabaseConnectionSource databaseConnectionSource = DatabaseConnectionSources.fromDataSource(dataSource);

        final Catalog catalog = SchemaCrawlerUtility.getCatalog(databaseConnectionSource, options);`

### Relevant log output

```shell
java.io.IOException: Cannot read classpath resource, </postgresql.information_schema/TABLE_COLUMN_PRIVILEGES.sql>
	at us.fatehi.utility.ioresource.ClasspathInputResource.<init>(ClasspathInputResource.java:50) ~[schemacrawler-16.23.2.jar:?]
	at us.fatehi.utility.IOUtility.readResourceFully(IOUtility.java:208) ~[schemacrawler-16.23.2.jar:?]
	at schemacrawler.schemacrawler.InformationSchemaViewsBuilder.fromResourceFolder(InformationSchemaViewsBuilder.java:91) ~[schemacrawler-16.23.2.jar:?]
	at schemacrawler.server.postgresql.PostgreSQLDatabaseConnector.lambda$new$1(PostgreSQLDatabaseConnector.java:44) ~[schemacrawler-postgresql-16.23.2.jar:?]
	at schemacrawler.schemacrawler.InformationSchemaViewsBuilder.withFunction(InformationSchemaViewsBuilder.java:121) ~[schemacrawler-16.23.2.jar:?]
	at schemacrawler.tools.databaseconnector.DatabaseConnector.getSchemaRetrievalOptionsBuilder(DatabaseConnector.java:123) ~[schemacrawler-16.23.2.jar:?]
	at schemacrawler.tools.utility.SchemaCrawlerUtility.buildSchemaRetrievalOptions(SchemaCrawlerUtility.java:209) ~[schemacrawler-16.23.2.jar:?]
	at schemacrawler.tools.utility.SchemaCrawlerUtility.matchSchemaRetrievalOptions(SchemaCrawlerUtility.java:145) ~[schemacrawler-16.23.2.jar:?]
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:78) ~[schemacrawler-16.23.2.jar:?]
```

### SchemaCrawler Version

16.23.2

### Java Version

21

### Operating System and Version

windows11

### Relational Database System and Version

postgresql 16.4

### JDBC Driver and Version

org.postgresql:postgresql:42.7.4

**Comment by sualeh** [comment]
这是一个警告，不会产生任何影响。我将在下一个版本中将其降低到较低的严重级别。

This is a warning, and will not have any impact. I will reduce it to a lower severity level in the next release.
