### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: syntax error at or near "graph" 

### ISSUE THREAD

**Issue by savita-malaghan** [schemacrawler/SchemaCrawler#206]
getting error with this version: 15.01.02
# Issue
Sep 20, 2018 7:26:09 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Unknown command <graph>: ERROR: syntax error at or near "graph"
  Position: 1
schemacrawler.schemacrawler.SchemaCrawlerException: Unknown command <graph>: ERROR: syntax error at or near "graph"
  Position: 1
	at schemacrawler.tools.text.operation.OperationCommand.execute(OperationCommand.java:153)
	at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:132)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:135)
	at schemacrawler.Main.main(Main.java:92)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "graph"
  Position: 1
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at sf.util.DatabaseUtility.executeSql(DatabaseUtility.java:166)
	at schemacrawler.tools.text.operation.OperationCommand.execute(OperationCommand.java:142)
	... 3 more

**Comment by sualeh** [comment]
"graph" is not a supported SchemaCrawler command. Please run SchemaCrawler without any command-line arguments for help. Please see [diagramming](https://www.schemacrawler.com/diagramming.html) on the SchemaCrawler website for more information too.

**Comment by adriens** [comment]
`graph `has been replaced by `schema`
