### ISSUE TITLE
Bad jdbc url generation for Oracle thin driver

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#240]
# Issue

When I try to connect to Oracle, I see that the generated jdbc thin url is not the good one.
Actually it is :

 `jdbc:oracle:thin:@//localhost:1521/DIDI3`

while it should be :

`jdbc:oracle:thin:@localhost:1521:DIDI3`

See explicit schemacrawler logs below :

generated after my command :

```
schemacrawler -server=oracle -host=localhost -port=1521 -database=DIDI3 -user=hr -password=tiger -c=csv -loglevel=CONFIG
```

```
-loglevel=CONFIG
dÚc. 29, 2018 8:59:12 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
GRAVE: Could not connect to jdbc:oracle:thin:@//localhost:1521/DIDI3, for user 'hr', with properties {}
schemacrawler.schemacrawler.SchemaCrawlerSQLException: Could not connect to jdbc:oracle:thin:@//localhost:1521/DIDI3, for user 'hr', with properties {}
        at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:187)
        at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getConnection(BaseDatabaseConnectionOptions.java:103)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:120)
        at schemacrawler.Main.main(Main.java:92)
```
See the successfull Squirrel session below :

![2018-12-29 21_07_27-squirrel sql client snapshot-20180815_2231](https://user-images.githubusercontent.com/5235127/50536917-e7efa200-0bad-11e9-9c58-e37de685ed43.png)

# Environment

> Schemacrawler `15.03.03`
> Schemacrawler > `1.8`
> Operating system `Windows`
> Database : `Oracle`
> [Oracle official JDBC driver](https://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html) `ojdbc7.jar` (with SHA1 Checksum `a2348e4944956fac05235f7cd5d30bf872afb157`)

**Comment by adriens** [comment]
Btw, the direct connexion with jdbc url connexion works : 

`schemacrawler -url=jdbc:oracle:thin:@localhost:1521:DIDI3 -u=hr -password=tiger -c=csv`

**Comment by sualeh** [comment]
@adriens, please send me the complete SchemaCrawler log. Thanks.

**Comment by adriens** [comment]
The schemacrawler CLI expects the `SERVICE_NAME`

`schemacrawler -url=jdbc:oracle:thin:@//localhost:1521/DIDI3.site-mairie.noumea.nc -u=hr -password=tiger -c=csv -loglevel=CONFIG`

and it works 👍

**Comment by adriens** [comment]
It also works with native `oracle` switch : 

`schemacrawler -server=oracle -host=localhost -port=1521 -database=DIDI3.site-mairie.noumea.nc -user=hr -password=tiger -c=csv`
