### ISSUE TITLE
getDbCatalogName() not working on my command on my locally installed Oracle

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#241]
# Issue

The following code

```java
private String getDbCatalogName()
  {
    String dbCatalogName = "";
    final Map<String, String> serverInfoMap = new HashMap<>();
    for (final Property serverInfoProperty: catalog.getDatabaseInfo()
      .getServerInfo())
    {
      serverInfoMap.put(serverInfoProperty.getName(),
                        serverInfoProperty.getValue().toString());
    }
    LOGGER.info("MAP : " + serverInfoMap.toString());

    if (serverInfoMap.containsKey("SERVICE_NAME"))
    {
      // Oracle SERVICE_NAME
      dbCatalogName = serverInfoMap.get("SERVICE_NAME");
    }
    else if (serverInfoMap.containsKey("current_database"))
    {
      // PostgreSQL current_database
      dbCatalogName = serverInfoMap.get("current_database");
    }
    else if (serverInfoMap.containsKey("ServerName"))
    {
      // Microsoft SQL Server ServerName
      dbCatalogName = serverInfoMap.get("ServerName");
    }
    else if (serverInfoMap.containsKey("CATALOG_NAME"))
    {
      // HyperSQL (HSQLDB) CATALOG_NAME
      dbCatalogName = serverInfoMap.get("CATALOG_NAME");
    }

    return dbCatalogName;
  }
```

does not get the oracle `SID` : the map remains empty.
# Environment

> Specify the
> * version of SchemaCrawler that you are using : `15.03.03`
> * version of Java that you are using `1.8`
> * operating system and version that you are using `Windows`
> * relational database and version that you are using `Oracle`
> * JDBC driver and version that you are using `ojdbc7.jar`

**Comment by adriens** [comment]
I'm usin `hr` user so we can test on standard privileged user 👍

**Comment by adriens** [comment]
Here is the log from the following command line :

`schemacrawler -url=jdbc:oracle:thin:@localhost:1521:DIDI3 -u=hr -password=tiger -c=csv  -loglevel=CONFIG -infolevel=maximum`

[schemacrawler.log](https://github.com/schemacrawler/SchemaCrawler/files/2716741/schemacrawler.log)

**Comment by adriens** [comment]
Here it is : you're trying to read a table for which you have not sufficent privileges :

```
AVERTISSEMENT: Error executing SQL <SELECT TABLE_NAME FROM DBA_TABLES WHERE ROWNUM = 1>
java.sql.SQLSyntaxErrorException: ORA-00942: Table ou vue inexistante

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
```

**Comment by adriens** [comment]
It'a `DBA_*` table, that' why.

**Comment by adriens** [comment]
Try this one instead :

```sql
select name from  v$database;
```

**Comment by sualeh** [comment]
This is the code that SchemaCrawler uses:
```sql
SELECT
  'SERVICE_NAME' AS NAME,
  SERVICE_NAME AS VALUE,
  '' AS DESCRIPTION
FROM
  V$SESSION
WHERE
  SID IN (SELECT DISTINCT SID FROM V$MYSTAT)
UNION ALL
SELECT
  'SID' AS NAME,
  INSTANCE AS VALUE,
  '' AS DESCRIPTION
FROM
  V$THREAD
```

**Comment by adriens** [comment]
Here is the ouput with `hr` user :

```
SQL> SELECT
  2    'SERVICE_NAME' AS NAME,
  3    SERVICE_NAME AS VALUE,
  4    '' AS DESCRIPTION
  5  FROM
  6    V$SESSION
  7  WHERE
  8    SID IN (SELECT DISTINCT SID FROM V$MYSTAT)
  9  UNION ALL
 10  SELECT
 11    'SID' AS NAME,
 12    INSTANCE AS VALUE,
 13    '' AS DESCRIPTION
 14  FROM
 15    V$THREAD;
  SID IN (SELECT DISTINCT SID FROM V$MYSTAT)
                                   *
ERREUR Ó la ligne 8 :
ORA-00942: Table ou vue inexistante
```

**Comment by adriens** [comment]
SO you want to grab the `SERVICE_NAME` ?

**Comment by adriens** [comment]
We have to find the view that requires as less privileges as possible...

**Comment by sualeh** [comment]
Please find the Service Name, and use it for the `-database=<service_name>` command-line argument.

**Comment by sualeh** [comment]
Ok, let me set up a user with minimum privileges, and see.

**Comment by adriens** [comment]
Check the `global_name` view : no grant required : 

```
C:\Users\salad74>sqlplus hr/tiger

SQL*Plus: Release 12.2.0.1.0 Production on Dim. DÚc. 30 09:09:15 2018

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Heure de la derniÞre connexion rÚussie : Dim. DÚc.  30 2018 09:03:51 +11:00

ConnectÚ Ó :
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL> select * from global_name;

GLOBAL_NAME
--------------------------------------------------------------------------------
DIDI3.SITE-MAIRIE.NOUMEA.NC

SQL> sho user
USER est "HR"
```

**Comment by adriens** [comment]
Naming the column makes things a bit cleaner :

```
SQL> select global_name from global_name;

GLOBAL_NAME
--------------------------------------------------------------------------------
DIDI3.SITE-MAIRIE.NOUMEA.NC
```

**Comment by sualeh** [comment]
No. We need to find SQL to get the MySQL catalog name.

**Comment by adriens** [comment]
See https://github.com/schemacrawler/SchemaCrawler/issues/243
