### ISSUE TITLE
Schema creation for *.sqlite file fails on macOS

### ISSUE THREAD

**Issue by regetskcob** [schemacrawler/SchemaCrawler#255]
# Issue

When I run the following command-line command in the macOS Terminal, I get the following two exceptions and nothing else happens.

## Command
```
./schemacrawler.sh -server=sqlite -database=/Users/dbocksteger/Desktop/infopoint.db -infolevel=maximum -password= -command=schema -outputformat=png -outputfile=infopoint_schmea.png -loglevel=ALL
```

### 1. Exception
```
Jun 26, 2019 8:03:33 AM schemacrawler.utility.ProcessExecutor call
SCHWERWIEGEND: Cannot run program "dot": error=2, No such file or directory
java.io.IOException: Cannot run program "dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at schemacrawler.utility.ProcessExecutor.call(ProcessExecutor.java:80)
	at schemacrawler.tools.integration.graph.GraphvizUtility.isGraphvizAvailable(GraphvizUtility.java:36)
	at schemacrawler.tools.integration.graph.GraphRenderer.checkAvailibility(GraphRenderer.java:78)
	at schemacrawler.tools.executable.BaseCommandChain.checkAvailibilityChain(BaseCommandChain.java:112)
	at schemacrawler.tools.executable.CommandDaisyChain.execute(CommandDaisyChain.java:112)
	at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:133)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:134)
	at schemacrawler.Main.main(Main.java:92)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:185)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
```

### 2. Exception
```
Jun 26, 2019 8:03:33 AM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SCHWERWIEGEND: guru/nidi/graphviz/engine/Format
java.lang.NoClassDefFoundError: guru/nidi/graphviz/engine/Format
	at schemacrawler.tools.integration.graph.GraphvizJavaExecutorUtility.map(GraphvizJavaExecutorUtility.java:150)
	at schemacrawler.tools.integration.graph.GraphvizJavaExecutorUtility.canMap(GraphvizJavaExecutorUtility.java:32)
	at schemacrawler.tools.integration.graph.GraphvizJavaExecutorUtility.isGraphvizJavaAvailable(GraphvizJavaExecutorUtility.java:81)
	at schemacrawler.tools.integration.graph.GraphRenderer.checkAvailibility(GraphRenderer.java:83)
	at schemacrawler.tools.executable.BaseCommandChain.checkAvailibilityChain(BaseCommandChain.java:112)
	at schemacrawler.tools.executable.CommandDaisyChain.execute(CommandDaisyChain.java:112)
	at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:133)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:134)
	at schemacrawler.Main.main(Main.java:92)
Caused by: java.lang.ClassNotFoundException: guru.nidi.graphviz.engine.Format
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

Forthermore, I would like to attach the logs, but I don't get were to find them? Would like to attach them later, after anybody told me where I get them 👍 

# Environment
* SchemaCrawler 15.06.01
* Mac OS X 10.14.5
* Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13

**Comment by sualeh** [comment]
Please install Graphviz first. You can do a Google search on how to do this. I found one resource - http://macappstore.org/graphviz-2/ but your mileage may vary.

**Comment by sualeh** [comment]
@regetskcob - did installing Graphviz help?

**Comment by regetskcob** [comment]
> Please install Graphviz first. You can do a Google search on how to do this. I found one resource - http://macappstore.org/graphviz-2/ but your mileage may vary.

That did the trick :-) Is working fine now!
