### ISSUE TITLE
Daterange index in Postgres results in NotLoadedException for details diagram

### ISSUE THREAD

**Issue by duncan-truss** [schemacrawler/SchemaCrawler#458]
# Bug Report

**Issue**

While trying to generate a details diagram to include the table indexes, the command results in a NotLoadedException that points to an issue parsing a table with an exclusion gist constraint for a daterange of two columns.

For instance the table had a constraint specified like so:
```sql
CREATE TABLE prices {
    start_date date NOT NULL,
    end_date date NOT NULL,
    CONSTRAINT exclude_dates EXCLUDE using gist (daterange(start_date,end_date,'[]') WITH &&)
}
```

The command I ran was:

```
docker run \
--mount type=bind,source="$(pwd)",target=/home/schcrwlr \
--rm -it \
schemacrawler/schemacrawler \
/opt/schemacrawler/schemacrawler.sh \
--server=postgresql \
--command=details \
--output-format=svg \
--output-file=graph.svg \
--portable-names \
--info-level=maximum \
```

The Schemacrawler output:
```
SEVERE: Cannot execute SchemaCrawler command
picocli.CommandLine$ExecutionException: Cannot execute SchemaCrawler command
	at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:148)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.executeCommandLine(SchemaCrawlerCommandLine.java:99)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:67)
	at schemacrawler.Main.main(Main.java:73)
Caused by: schemacrawler.crawl.NotLoadedException: Complete metadata has not been loaded for <public.prices."daterange(start_date, end_date, '[]'::text)">
	at schemacrawler.crawl.ColumnPartial.getColumnDataType(ColumnPartial.java:60)
	at schemacrawler.crawl.MutableKeyColumn.getColumnDataType(MutableKeyColumn.java:79)
	at schemacrawler.utility.MetaDataUtility.joinColumns(MetaDataUtility.java:243)
	at schemacrawler.utility.MetaDataUtility.joinColumns(MetaDataUtility.java:285)
	at schemacrawler.utility.MetaDataUtility.getColumnsListAsString(MetaDataUtility.java:143)
	at schemacrawler.tools.text.formatter.diagram.SchemaDotFormatter.printIndexes(SchemaDotFormatter.java:491)
	at schemacrawler.tools.text.formatter.diagram.SchemaDotFormatter.handle(SchemaDotFormatter.java:192)
	at schemacrawler.tools.traversal.SchemaTraverser.traverse(SchemaTraverser.java:112)
	at schemacrawler.tools.command.text.diagram.DiagramRenderer.execute(DiagramRenderer.java:110)
	at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:109)
	at schemacrawler.tools.commandline.command.ExecuteCommand.run(ExecuteCommand.java:146)
	... 3 more

SchemaCrawler 16.14.3

Error: Complete metadata has not been loaded for <public.prices."daterange(start_date, end_date, '[]'::text)">
```

**Environment**

SchemaCrawler version 16.14.3
Postgres version 12.4

**Comment by sualeh** [comment]
@duncan-truss - please use SchemaCrawler 16.14.4

**Comment by duncan-truss** [comment]
@sualeh That was an incredibly quick bug fix!  I tried the newest version and no longer receive the exception hooray!  It's really useful that the comments are included in the diagram output as well.
