### ISSUE TITLE
`EmbeddedDiagramRenderer` calls `scCommand.checkAvailability()` before `scCommand.initialize()`

### ISSUE THREAD

**Issue by marcust** [schemacrawler/SchemaCrawler#465]
# Bug Report

**Issue**

Please explain the issue briefly
* I am trying to programmatically render `htmlx` files without GraphViz `dot` installed. 
* I basically copied https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-examplecode/src/main/java/com/example/ExecutableExample.java into Gradle and modified the output format
* This leads to a NPE:
```
Caused by: java.lang.NullPointerException: Cannot invoke "schemacrawler.tools.command.text.diagram.options.DiagramOutputFormat.getDescription()" because "diagramOutputFormat" is null
        at schemacrawler.tools.command.text.diagram.GraphvizUtility.isGraphvizJavaAvailable(GraphvizUtility.java:75)
        at schemacrawler.tools.command.text.diagram.DiagramRenderer.checkAvailability(DiagramRenderer.java:67)
        at schemacrawler.tools.command.text.embeddeddiagram.EmbeddedDiagramRenderer.executeCommand(EmbeddedDiagramRenderer.java:158)
        at schemacrawler.tools.command.text.embeddeddiagram.EmbeddedDiagramRenderer.execute(EmbeddedDiagramRenderer.java:113)
        at schemacrawler.tools.executable.SchemaCrawlerExecutable.execute(SchemaCrawlerExecutable.java:109)
```
 * The reason seems to be that `diagramOutputFormat` in `DiagramRenderer` is only set in the `initialize()` method, which is called after the `checkAvailability()` call in the `EmbeddedDiagramRenderer.executeCommand` .

**Environment**

* Version is `16.14.5`
* no GraphViz installed, so `dot` is not available
* I added `guru.nidi:graphviz-java:0.18.1` to my classpath

**Comment by sualeh** [comment]
Please use SchemaCrawler v16.14.6
