### ISSUE TITLE
java.io.NotSerializableException: schemacrawler.crawl.SynonymRetriever

### ISSUE THREAD

**Issue by pungaa** [schemacrawler/SchemaCrawler#482]
# Bug Report

**Issue**

I am crawling a oracle database that has synonyms, when I serialize the catalog object to Java ser using JavaSerializedCatalog.save() I get the following error. 

schemacrawler.schemacrawler.SchemaCrawlerException: Could not serialize catalog: schemacrawler.crawl.SynonymRetriever
	at schemacrawler.tools.formatter.serialize.JavaSerializedCatalog.save(JavaSerializedCatalog.java:76)
Caused by: java.io.NotSerializableException: schemacrawler.crawl.SynonymRetriever
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1793)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1154)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at schemacrawler.tools.formatter.serialize.JavaSerializedCatalog.save(JavaSerializedCatalog.java:74)

**Environment**
schemaCrawlerVersion" : "16.14.6",
"databaseInfoProductName" : "Oracle",
  "databaseInfoProductVersion" : "Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production",
  "jdbcDriverInfoDriverClassName" : "oracle.jdbc.OracleDriver",
  "jdbcDriverInfoProductVersion" : "19.3.0.0.0"

**Comment by pungaa** [comment]
in SynonymRetriever Line 138. New AbstractDatabaseObject() is retuning a object of type SynonymRetriever

```
         referencedObject =
              new AbstractDatabaseObject(referencedSchema, referencedObjectName) {
                private static final long serialVersionUID = -2212843304418302122L;
              };
```

**Comment by sualeh** [comment]
Thanks - that makes sense. Let me reproduce it, so that I can be sure I have fixed it.

**Comment by pungaa** [comment]
Thanks! Let me know how I can help in any way

**Comment by sualeh** [comment]
@pungaa please use SchemaCrawler v16.15.2
