### ISSUE TITLE
Database Connection issues with latest (16.15.7) docker image

### ISSUE THREAD

**Issue by mariokoehler** [schemacrawler/SchemaCrawler#511]
# Bug Report

Since the release of the 16.15.7 our SchemaCrawler is unable to get a connection to our database. Convertig back to the previous version resolves the issue. The problem seems to be related to SSL handshake issues, maybe related to upgrade to JDK 17?

Our SchemaCrawler runs in a Github Actions pipeline and connects to an Amazon (AWS) Aurora/MySql database. All necessary permissions (security groups etc.) have been granted on the AWS side (as proven with the 16.15.6 version, which can connect to the database)

this is the error we get:

`2021-09-21T07:37:30.5792037Z Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
2021-09-21T07:37:30.5794022Z 	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
2021-09-21T07:37:30.5796035Z 	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
2021-09-21T07:37:30.5798178Z 	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:238)
2021-09-21T07:37:30.5800291Z 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
2021-09-21T07:37:30.5802403Z 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
2021-09-21T07:37:30.5804800Z 	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:320)
2021-09-21T07:37:30.5807732Z 	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:194)
2021-09-21T07:37:30.5811039Z 	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:101)
2021-09-21T07:37:30.5814931Z 	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:308)
2021-09-21T07:37:30.5816823Z 	... 16 more
`
the full log is attached.

[schemacrawler.log](https://github.com/schemacrawler/SchemaCrawler/files/7201521/schemacrawler.log)
.

**Comment by sualeh** [comment]
Also, please run the following command on your Amazon (AWS) Aurora/ MySQL database.

```sql
SHOW GLOBAL VARIABLES LIKE 'tls_version';
```

**Comment by mariokoehler** [comment]
I'll give it a try and let you know how it went. Thanks for your support!

**Comment by mariokoehler** [comment]
btw...output from the "show global" was:

TLSv1,TLSv1.1,TLSv1.2

**Comment by mariokoehler** [comment]
I tested your suggested parameter variation and it works, the error is gone.

Thank you again for your support!
