### ISSUE TITLE
[Issue]: Offline connection does not support method, toString

### ISSUE THREAD

**Issue by pioneer2k** [schemacrawler/SchemaCrawler#535]
### Description

I am using the Docker variant of SchemaCrawler 16.15.11 with a MySQL 5.7 database and tried the "offline schema" feature. Generating the offline schema as JSON or YAML works very well. But generating a diagram of that offline schema leads to the following exception:

```
Nov 08, 2021 8:36:19 AM schemacrawler.tools.commandline.utility.CommandLineLoggingUtility logFatalStackTrace
SEVERE: null
java.lang.reflect.UndeclaredThrowableException
        at jdk.proxy2/jdk.proxy2.$Proxy13.toString(Unknown Source)
        at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3057)
        at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2934)
        at java.base/java.util.Formatter.format(Formatter.java:2690)
        at java.base/java.util.Formatter.format(Formatter.java:2625)
        at us.fatehi.utility.string.StringFormat.get(StringFormat.java:52)
        at us.fatehi.utility.string.StringFormat.get(StringFormat.java:35)
        at java.logging/java.util.logging.Logger.log(Logger.java:1050)
        at schemacrawler.tools.databaseconnector.DatabaseConnectionSource.getConnection(DatabaseConnectionSource.java:185)
        at schemacrawler.tools.databaseconnector.DatabaseConnectionSource.get(DatabaseConnectionSource.java:84)
        at schemacrawler.tools.databaseconnector.DatabaseConnectionSource.get(DatabaseConnectionSource.java:53)
        at schemacrawler.tools.commandline.command.ConnectCommand.loadSchemaRetrievalOptionsBuilder(ConnectCommand.java:186)
        at schemacrawler.tools.commandline.command.ConnectCommand.run(ConnectCommand.java:126)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.executeCommandLine(SchemaCrawlerCommandLine.java:99)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:67)
        at schemacrawler.Main.main(Main.java:73)
Caused by: java.sql.SQLFeatureNotSupportedException: Offline connection does not support method, toString
        at schemacrawler.tools.offline.jdbc.OfflineConnectionUtility$OfflineConnectionInvocationHandler.invoke(OfflineConnectionUtility.java:66)
        ... 16 more` 
```

### Reproduce

These are my command line options for generating the offline schema:
`--info-level=maximum --command serialize --portable-names=true --sort-columns=false --output-format=yaml --output-file=er_graph.yml --load-row-counts=false --log-level=ALL`

These are my command line options for using the offline schema to generate a diagram:
`--server=offline --database=/home/schcrwlr/er_graph.yml --info-level=standard --command=details --portable-names=true --sort-columns=false --output-format=png --output-file=er_graph.png --load-row-counts=false --log-level=ALL`

### Relevant log output

see description

### SchemaCrawler Version

16.15.11

### Java Version

Oracle Corporation OpenJDK 64-Bit Server VM 17-ea+14

### Operating System and Version

Windows 10

### Relational Database System and Version

MySQL 5.7 (AWS Aurora)

### JDBC Driver and Version

Unknown, running inside docker

**Comment by pioneer2k** [comment]
@sualeh Thank you for your hint. But event with --output-format=ser the error stays absolutely the same:

`Nov 09, 2021 6:59:40 AM schemacrawler.tools.commandline.utility.CommandLineLoggingUtility logSafeArguments
INFO: Command line:
--server=offline
--database=/home/schcrwlr/er_graph.ser
--info-level=standard
--command=details
--portable-names=true
--sort-columns=false
--output-format=png
--output-file=er_graph.png
--load-row-counts=false
--log-level=ALL
Nov 09, 2021 6:59:40 AM schemacrawler.tools.commandline.utility.CommandLineLoggingUtility logFatalStackTrace
SEVERE: null
java.lang.reflect.UndeclaredThrowableException
        at jdk.proxy2/jdk.proxy2.$Proxy13.toString(Unknown Source)
        at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3057)
        at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2934)
        at java.base/java.util.Formatter.format(Formatter.java:2690)
        at java.base/java.util.Formatter.format(Formatter.java:2625)
        at us.fatehi.utility.string.StringFormat.get(StringFormat.java:52)
        at us.fatehi.utility.string.StringFormat.get(StringFormat.java:35)
        at java.logging/java.util.logging.Logger.log(Logger.java:1050)
        at schemacrawler.tools.databaseconnector.DatabaseConnectionSource.getConnection(DatabaseConnectionSource.java:185)
        at schemacrawler.tools.databaseconnector.DatabaseConnectionSource.get(DatabaseConnectionSource.java:84)
        at schemacrawler.tools.databaseconnector.DatabaseConnectionSource.get(DatabaseConnectionSource.java:53)
        at schemacrawler.tools.commandline.command.ConnectCommand.loadSchemaRetrievalOptionsBuilder(ConnectCommand.java:186)
        at schemacrawler.tools.commandline.command.ConnectCommand.run(ConnectCommand.java:126)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.executeCommandLine(SchemaCrawlerCommandLine.java:99)
        at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:67)
        at schemacrawler.Main.main(Main.java:73)
Caused by: java.sql.SQLFeatureNotSupportedException: Offline connection does not support method, toString
        at schemacrawler.tools.offline.jdbc.OfflineConnectionUtility$OfflineConnectionInvocationHandler.invoke(OfflineConnectionUtility.java:66)
        ... 16 more

SchemaCrawler 16.15.11`

**Comment by sualeh** [comment]
@pioneer2k - for now, please run it without any `--log-level`, and I will take a look.

**Comment by pioneer2k** [comment]
@sualeh Nice hint. Without any --log-level it works very well. I testet with png, html and htmlx.

**Comment by sualeh** [comment]
@pioneer2k - I will fix the logging issue in the next release of SchemaCrawler, which will be soon.

**Comment by sualeh** [comment]
@pioneer2k - please use SchemaCrawler 16.16.02 to use logging with offline connections.
