### ISSUE TITLE
Problem fetching table columns with name containing "/" - forward slash

### ISSUE THREAD

**Issue by siggemannen** [schemacrawler/SchemaCrawler#628]
### Description

Hello, and thanks for great lib!
I'm using schemacrawling-api 16.16.11 against oracle express.
When fetching column info for table containg a "/" it crashes with incorrect escape character error:

```
Caused by: schemacrawler.schemacrawler.exceptions.WrappedSQLException: Could not retrieve table columns for table <"xyz/abc">: ORA-01424......
	at schemacrawler.crawl.TableColumnRetriever.retrieveTableColumnsFromMetadata(TableColumnRetriever.java:283)
	at schemacrawler.crawl.TableColumnRetriever.retrieveTableColumns(TableColumnRetriever.java:96)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$13(SchemaCrawler.java:381)
	at schemacrawler.crawl.RetrievalStopWatch.lambda$time$0(RetrievalStopWatch.java:105)
	at us.fatehi.utility.StopWatch.time(StopWatch.java:142)
	at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:100)
	at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:72)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:377)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:144)

```

This is because the final sql generated by oracle is something like:

select ...
from all_tab_cols t
WHERE t.table_name LIKE 'xyz/abc' ESCAPE '/'

But / is part of escape sequence, and needs to be escaped by /.

Suggested fix: It's either oracle jdbc bug (i mean they should escape the table name themselves), or schemacrawler have to escape table name when passing it in the TableColumnRetriever#retrieveTableColumnsFromMetadata:

```java
getMetaData()
.getColumns(
table.getSchema().getCatalogName(),
table.getSchema().getName(), 
table.getName(), //replace / with // for oracle??
null)
```

### How to Reproduce

```markdown
1. Create a table in oracle express (or i'm suspecting most other oracle versions) with a slash:

create table "a/b" (i int)

2. Try to crawl this table.
```

### Relevant log output

```shell
feb 28, 2022 11:36:26 EM schemacrawler.tools.utility.SchemaCrawlerUtility buildSchemaRetrievalOptions
INFO: Using database plugin for 
feb 28, 2022 11:36:27 EM schemacrawler.tools.utility.SchemaCrawlerUtility logConnection
INFO: Connected to 
Oracle Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0 
using JDBC driver 
Oracle JDBC driver 19.7.0.0.0
with 
"jdbc:oracle:thin:oracle-REDACTED"
feb 28, 2022 11:36:27 EM schemacrawler.crawl.SchemaCrawler crawlDatabaseInfo
INFO: Not retrieving database information, since this was not requested
feb 28, 2022 11:36:27 EM schemacrawler.crawl.SchemaCrawler crawl
INFO: 
-- generated by: SchemaCrawler 16.16.11
-- generated on: 2022-02-28T22:36:27.132
-- database: Oracle Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
-- driver: Oracle JDBC driver 19.7.0.0.0
-- operating system: Windows 7 6.1
-- JVM system: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_212-b10

feb 28, 2022 11:36:27 EM schemacrawler.crawl.RetrievalStopWatch lambda$time$0
INFO: Running retrieveSchemas
feb 28, 2022 11:36:27 EM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
INFO: Retrieving all schemas
feb 28, 2022 11:36:27 EM schemacrawler.crawl.SchemaRetriever retrieveAllCatalogs
INFO: Retrieving all catalogs
feb 28, 2022 11:36:27 EM schemacrawler.crawl.SchemaRetriever retrieveAllSchemas
INFO: Processed 36 schemas
feb 28, 2022 11:36:27 EM schemacrawler.crawl.RetrievalStopWatch lambda$time$0
INFO: Running filterAndSortSchemas
feb 28, 2022 11:36:27 EM schemacrawler.crawl.SchemaCrawler crawlSchemas
INFO: Retrieved 36 schemas
feb 28, 2022 11:36:27 EM schemacrawler.crawl.RetrievalStopWatch lambda$time$0
INFO: Running retrieveColumnDataTypes
feb 28, 2022 11:36:27 EM schemacrawler.crawl.DataTypeRetriever retrieveSystemColumnDataTypes
INFO: Retrieving system column data types
feb 28, 2022 11:36:27 EM schemacrawler.crawl.DataTypeRetriever retrieveSystemColumnDataTypesFromMetadata
INFO: Processed 28 system column data types
feb 28, 2022 11:36:27 EM schemacrawler.crawl.RetrievalStopWatch lambda$time$0
INFO: retrieveUserDefinedColumnDataTypes not requested
feb 28, 2022 11:36:27 EM schemacrawler.crawl.RetrievalStopWatch lambda$time$0
INFO: Running retrieveTables
feb 28, 2022 11:36:27 EM schemacrawler.crawl.SchemaCrawler lambda$crawlTables$12
INFO: Retrieving table names
feb 28, 2022 11:36:27 EM schemacrawler.crawl.TableRetriever retrieveTables
INFO: Retrieving tables
INFO: Processed 60 tables
...REDACTED...
feb 28, 2022 11:36:35 EM schemacrawler.crawl.SchemaCrawler crawlTables
INFO: Retrieved 3006 tables
feb 28, 2022 11:36:35 EM schemacrawler.crawl.RetrievalStopWatch lambda$time$0
INFO: Running retrieveTableColumns
feb 28, 2022 11:36:35 EM schemacrawler.crawl.TableColumnRetriever retrieveHiddenTableColumnsLookupKeys
INFO: No hidden table columns SQL provided
feb 28, 2022 11:36:35 EM schemacrawler.crawl.TableColumnRetriever retrieveTableColumns
INFO: Retrieving table columns
feb 28, 2022 11:40:12 EM schemacrawler.crawl.RetrievalStopWatch stopAndLogTime
INFO: Total time taken for <> - 00:00:08.712 hours
-  1,8% - 00:00:00.156 - <retrieveSchemas>
-  0,2% - 00:00:00.017 - <filterAndSortSchemas>
-  2,2% - 00:00:00.193 - <retrieveColumnDataTypes>
-  0,0% - 00:00:00.002 - <retrieveUserDefinedColumnDataTypes>
- 95,8% - 00:00:08.344 - <retrieveTables>

schemacrawler.schemacrawler.exceptions.ExecutionRuntimeException: Could not retrieve table columns for table <"REDACTED"."SYS_NT3XwABOchOP/gQyWq6ArfyA==">: ORA-01424: REDACTED

	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:153)
	at schemacrawler.tools.catalogloader.SchemaCrawlerCatalogLoader.loadCatalog(SchemaCrawlerCatalogLoader.java:58)
	at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:76)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:101)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:81)

Caused by: schemacrawler.schemacrawler.exceptions.WrappedSQLException: Could not retrieve table columns for table <"REDACTED"."SYS_NT3XwABOchOP/gQyWq6ArfyA==">: ORA-01424: REDACTED

	at schemacrawler.crawl.TableColumnRetriever.retrieveTableColumnsFromMetadata(TableColumnRetriever.java:283)
	at schemacrawler.crawl.TableColumnRetriever.retrieveTableColumns(TableColumnRetriever.java:96)
	at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$13(SchemaCrawler.java:381)
	at schemacrawler.crawl.RetrievalStopWatch.lambda$time$0(RetrievalStopWatch.java:105)
	at us.fatehi.utility.StopWatch.time(StopWatch.java:142)
	at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:100)
	at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:72)
	at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:377)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:144)
	... 14 more
Caused by: java.sql.SQLDataException: ORA-01424: REDACTED

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
	at oracle.jdbc.driver.T4CStatement.fetch(T4CStatement.java:1037)
	at oracle.jdbc.driver.OracleStatement.fetchMoreRows(OracleStatement.java:3456)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.fetchMoreRows(InsensitiveScrollableResultSet.java:742)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.absoluteInternal(InsensitiveScrollableResultSet.java:698)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.next(InsensitiveScrollableResultSet.java:412)
	at schemacrawler.crawl.MetadataResultSet.next(MetadataResultSet.java:387)
	at schemacrawler.crawl.TableColumnRetriever.retrieveTableColumnsFromMetadata(TableColumnRetriever.java:278)
	... 22 more
Caused by: Error : 1424, Position : 2083, Sql = declare
  in_owner varchar2(256) := null;
  in_name varchar2(256) := null;
  in_column varchar2(256) := null;
  xyzzy SYS_REFCURSOR;
begin
  in_owner := :1 ;
  in_name := :2 ;
  in_column := :3 ;
open xyzzy for
SELECT NULL AS table_cat,
       t.owner AS table_schem,
       t.table_name AS table_name,
       t.column_name AS column_name,
  DECODE(substr(t.data_type, 1, 9), 
    'TIMESTAMP', 
      DECODE(substr(t.data_type, 10, 1), 
        '(', 
          DECODE(substr(t.data_type, 19, 5), 
            'LOCAL', -102, 'TIME ', -101, 93), 
        DECODE(substr(t.data_type, 16, 5), 
          'LOCAL', -102, 'TIME ', -101, 93)), 
    'INTERVAL ', 
      DECODE(substr(t.data_type, 10, 3), 
       'DAY', -104, 'YEA', -103), 
    DECODE(t.data_type, 
      'BINARY_DOUBLE', 101, 
      'BINARY_FLOAT', 100, 
      'BFILE', -13, 
      'BLOB', 2004, 
      'CHAR', 1, 
      'CLOB', 2005, 
      'COLLECTION', 2003, 
      'DATE', 93, 
      'FLOAT', 6, 
      'LONG', -1, 
      'LONG RAW', -4, 
      'NCHAR', -15, 
      'NCLOB', 2011, 
      'NUMBER', 2, 
      'NVARCHAR', -9, 
      'NVARCHAR2', -9, 
      'OBJECT', 2002, 
      'OPAQUE/XMLTYPE', 2009, 
      'RAW', -3, 
      'REF', 2006, 
      'ROWID', -8, 
      'SQLXML', 2009, 
      'UROWID', -8, 
      'VARCHAR2', 12, 
      'VARRAY', 2003, 
      'XMLTYPE', 2009, 
      DECODE((SELECT a.typecode 
        FROM ALL_TYPES a 
        WHERE a.type_name = t.data_type
       AND ((a.owner IS NULL AND 
t.data_type_owner IS NULL)
         OR (a.owner = t.data_type_owner))
        ), 
        'OBJECT', 2002, 
        'COLLECTION', 2003, 1111))) 
 AS data_type,
       t.data_type AS type_name,
       DECODE (t.data_precision,                null, DECODE(t.data_type,                        'NUMBER', DECODE(t.data_scale,                                    null, 0                                   , 38),        DECODE (t.data_type,                'CHAR', t.char_length,                'VARCHAR', t.char_length,                'VARCHAR2', t.char_length,                'NVARCHAR2', t.char_length,                'NCHAR', t.char_length,                'NUMBER', 0,                t.data_length)                           ),         t.data_precision)
              AS column_size,
       0 AS buffer_length,
       DECODE (t.data_type,                'NUMBER', DECODE(t.data_precision,                                 null, DECODE(t.data_scale,                                              null, -127                                             , t.data_scale),                                  t.data_scale),                t.data_scale) AS decimal_digits,
       10 AS num_prec_radix,
       DECODE (t.nullable, 'N', 0, 1) AS nullable,
       NULL AS remarks,
       t.data_default AS column_def,
       0 AS sql_data_type,
       0 AS sql_datetime_sub,
       t.data_length AS char_octet_length,
       t.column_id AS ordinal_position,
       DECODE (t.nullable, 'N', 'NO', 'YES') AS is_nullable,
       null as SCOPE_CATALOG,
       null as SCOPE_SCHEMA,
       null as SCOPE_TABLE,
       null as SOURCE_DATA_TYPE,
       'NO' as IS_AUTOINCREMENT,
       t.virtual_column as IS_GENERATEDCOLUMN
FROM all_tab_cols t
WHERE t.owner LIKE in_owner ESCAPE '/'
  AND t.table_name LIKE in_name ESCAPE '/'
  AND t.column_name LIKE in_column ESCAPE '/'
  AND t.user_generated = 'YES'
ORDER BY table_schem, table_name, ordinal_position
; 
 :4  := xyzzy;
 end;, OriginalSql = declare
  in_owner varchar2(256) := null;
  in_name varchar2(256) := null;
  in_column varchar2(256) := null;
  xyzzy SYS_REFCURSOR;
begin
  in_owner := ?;
  in_name := ?;
  in_column := ?;
open xyzzy for
SELECT NULL AS table_cat,
       t.owner AS table_schem,
       t.table_name AS table_name,
       t.column_name AS column_name,
  DECODE(substr(t.data_type, 1, 9), 
    'TIMESTAMP', 
      DECODE(substr(t.data_type, 10, 1), 
        '(', 
          DECODE(substr(t.data_type, 19, 5), 
            'LOCAL', -102, 'TIME ', -101, 93), 
        DECODE(substr(t.data_type, 16, 5), 
          'LOCAL', -102, 'TIME ', -101, 93)), 
    'INTERVAL ', 
      DECODE(substr(t.data_type, 10, 3), 
       'DAY', -104, 'YEA', -103), 
    DECODE(t.data_type, 
      'BINARY_DOUBLE', 101, 
      'BINARY_FLOAT', 100, 
      'BFILE', -13, 
      'BLOB', 2004, 
      'CHAR', 1, 
      'CLOB', 2005, 
      'COLLECTION', 2003, 
      'DATE', 93, 
      'FLOAT', 6, 
      'LONG', -1, 
      'LONG RAW', -4, 
      'NCHAR', -15, 
      'NCLOB', 2011, 
      'NUMBER', 2, 
      'NVARCHAR', -9, 
      'NVARCHAR2', -9, 
      'OBJECT', 2002, 
      'OPAQUE/XMLTYPE', 2009, 
      'RAW', -3, 
      'REF', 2006, 
      'ROWID', -8, 
      'SQLXML', 2009, 
      'UROWID', -8, 
      'VARCHAR2', 12, 
      'VARRAY', 2003, 
      'XMLTYPE', 2009, 
      DECODE((SELECT a.typecode 
        FROM ALL_TYPES a 
        WHERE a.type_name = t.data_type
       AND ((a.owner IS NULL AND 
t.data_type_owner IS NULL)
         OR (a.owner = t.data_type_owner))
        ), 
        'OBJECT', 2002, 
        'COLLECTION', 2003, 1111))) 
 AS data_type,
       t.data_type AS type_name,
       DECODE (t.data_precision,                null, DECODE(t.data_type,                        'NUMBER', DECODE(t.data_scale,                                    null, 0                                   , 38),        DECODE (t.data_type,                'CHAR', t.char_length,                'VARCHAR', t.char_length,                'VARCHAR2', t.char_length,                'NVARCHAR2', t.char_length,                'NCHAR', t.char_length,                'NUMBER', 0,                t.data_length)                           ),         t.data_precision)
              AS column_size,
       0 AS buffer_length,
       DECODE (t.data_type,                'NUMBER', DECODE(t.data_precision,                                 null, DECODE(t.data_scale,                                              null, -127                                             , t.data_scale),                                  t.data_scale),                t.data_scale) AS decimal_digits,
       10 AS num_prec_radix,
       DECODE (t.nullable, 'N', 0, 1) AS nullable,
       NULL AS remarks,
       t.data_default AS column_def,
       0 AS sql_data_type,
       0 AS sql_datetime_sub,
       t.data_length AS char_octet_length,
       t.column_id AS ordinal_position,
       DECODE (t.nullable, 'N', 'NO', 'YES') AS is_nullable,
       null as SCOPE_CATALOG,
       null as SCOPE_SCHEMA,
       null as SCOPE_TABLE,
       null as SOURCE_DATA_TYPE,
       'NO' as IS_AUTOINCREMENT,
       t.virtual_column as IS_GENERATEDCOLUMN
FROM all_tab_cols t
WHERE t.owner LIKE in_owner ESCAPE '/'
  AND t.table_name LIKE in_name ESCAPE '/'
  AND t.column_name LIKE in_column ESCAPE '/'
  AND t.user_generated = 'YES'
ORDER BY table_schem, table_name, ordinal_position
; 
 ? := xyzzy;
 end;, Error Msg = ORA-01424: REDACTED

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 35 more
```

### SchemaCrawler Version

16.16.11

### Java Version

8

### Operating System and Version

Windows 7

### Relational Database System and Version

Oracle Oracle Database 18c Express Edition Release 18.0.0.0.0

### JDBC Driver and Version

Oracle JDBC driver 19.7.0.0.0

**Comment by siggemannen** [comment]
Actually, when i thought about it, probably same problem can occur with other characters that have special meaning for "LIKE" searches. Also, simular issues might occur with owner and column "like" matches as well.
I see that SQL Server has some escaping done in it's implementation of SQLServerDatabaseMetaData#getColumns, so perhaps it's a Oracle jdbc driver bug efter all

**Comment by sualeh** [comment]
@siggemannen - yes, this looks like an Oracle driver bug. You may consider some other (not free) [Oracle JDBC drivers](https://www.cdata.com/drivers/oracledb/odbc/).

**Comment by sualeh** [comment]
I will take a look, and see if there is a possible workaround if you use the Oracle data dictionary. You can configure SchemaCrawler to use the data dictionary instead of plain JDBC `DatabaseMetaData#getColumns`.

**Comment by siggemannen** [comment]
I fixed it "locally" by manually loading column metadata resultset directly from raw Connection.
But i do wonder one thing, isn't it better to "survive" such bugs/errors and not just give up crawling altogether? Or at least maybe have it as option.
I mean wrapping each table crawl by a try catch?

**Comment by sualeh** [comment]
@siggemannen - please take a look at the tests in the commits referenced this issue - https://github.com/schemacrawler/SchemaCrawler/commit/679eb0acea47fdef6a99bdc7046d257d1d755a23

**Comment by siggemannen** [comment]
Hi, and thanks for the quick answer!
I tested and it works if i include the schemacrawler-oracle maven artifact.

Thanks for the help!
