### ISSUE TITLE
Failure in scanning a DB2 database in z/os

### ISSUE THREAD

**Issue by zarenbalisi3** [schemacrawler/SchemaCrawler#658]
### Description

A successful analysis of my tables and columns.  The issue is that SYSCAT does not exist, but most of the correlated data is in SYSIBM.  https://stackoverflow.com/questions/36353109/db2-on-zos-catalog-table-for-schemas.

### How to Reproduce

Utilize schemacrawler against DB2 for z/os

### Relevant log output

```shell
2022-02-23 15:49:39.305  INFO 46958 --- [           main] schemacrawler.crawl.RetrievalStopWatch   : Running retrieveTableColumns
2022-02-23 15:49:39.309  WARN 46958 --- [           main] us.fatehi.utility.DatabaseUtility        : Error executing SQL <SELECT
  NULLIF(1, 1) AS TABLE_CATALOG,
  STRIP(COLUMNS.TABSCHEMA) AS TABLE_SCHEMA,
  STRIP(COLUMNS.TABNAME) AS TABLE_NAME,
  STRIP(COLUMNS.COLNAME) AS COLUMN_NAME
FROM
  SYSCAT.COLUMNS AS COLUMNS
WHERE
  COLUMNS.HIDDEN = 'I'
ORDER BY
  COLUMNS.TABSCHEMA,
  COLUMNS.TABNAME,
  COLUMNS.COLNAME
WITH UR 
>

com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=SYSCAT.COLUMNS, DRIVER=4.26.14
       at com.ibm.db2.jcc.am.b7.a(b7.java:810) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.b7.a(b7.java:66) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.b7.a(b7.java:140) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.c(k4.java:2824) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.d(k4.java:2808) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.a(k4.java:2234) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.a(k4.java:2210) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.t4.ab.i(ab.java:201) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.t4.ab.b(ab.java:96) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.t4.p.a(p.java:32) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.t4.av.i(av.java:150) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.al(k4.java:2203) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.a(k4.java:3330) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.e(k4.java:1131) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at com.ibm.db2.jcc.am.k4.execute(k4.java:1110) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at us.fatehi.utility.DatabaseUtility.executeSql(DatabaseUtility.java:116) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.schemacrawler.QueryUtility.executeAgainstSchema(QueryUtility.java:69) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.MetadataResultSet.<init>(MetadataResultSet.java:94) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.TableColumnRetriever.retrieveHiddenTableColumnsLookupKeys(TableColumnRetriever.java:221) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.TableColumnRetriever.retrieveTableColumns(TableColumnRetriever.java:88) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.SchemaCrawler.lambda$crawlTables$13(SchemaCrawler.java:413) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.RetrievalStopWatch.lambda$time$0(RetrievalStopWatch.java:107) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at us.fatehi.utility.StopWatch.time(StopWatch.java:142) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:102) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.RetrievalStopWatch.time(RetrievalStopWatch.java:78) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.SchemaCrawler.crawlTables(SchemaCrawler.java:409) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:150) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.tools.catalogloader.SchemaCrawlerCatalogLoader.loadCatalog(SchemaCrawlerCatalogLoader.java:59) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:77) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:107) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
       at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:86) ~[cc-sql-agent-plugin-jdbc.jar:22.3.4]
      
```

### SchemaCrawler Version

16.16.11

### Java Version

11

### Operating System and Version

z/os

### Relational Database System and Version

DB2 for z/os version 11.5

### JDBC Driver and Version

https://github.com/schemacrawler/SchemaCrawler/blob/master/schemacrawler-db2/pom.xml#L51-55

**Comment by sualeh** [comment]
@zarenbalisi3 - can you try again without the schemacrawler-db2 jar on your CLASSPATH?

**Comment by sualeh** [comment]
@zarenbalisi3 - any updates?

**Comment by sualeh** [comment]
@zarenbalisi3 - any updates? Otherwise I will close this issue.

**Comment by zarenbalisi3** [comment]
Hi @sualeh , we've not been able to get access to the environment to test again and to close the issue. We will retest when we get access to a z/os environment. I appreciate the quick responses, and I apologize for the delay.

**Comment by sualeh** [comment]
@zarenbalisi3 - Please reopen when you are able to test.
