### ISSUE TITLE
Oracle SQLException when `multi-threading` turned on

### ISSUE THREAD

**Issue by ltxlouis** [schemacrawler/SchemaCrawler#835]
### Description

I don't know why, but when running against an Oracle db and `System.setProperty("SC_EXPERIMENTAL", "true")` is on, SQLExceptions are thrown.

## possible reason
[VIEW.sql](https://github.com/schemacrawler/SchemaCrawler/blob/065b6b5fbb2abf1e100c3475b5e38b4db45b7676/schemacrawler-oracle/src/main/resources/oracle.information_schema/VIEWS.sql) returns `VIEW_DEFINITION` which is of type `LONG`.

[Reference](https://blog.jooq.org/oracle-long-and-long-raw-causing-stream-has-already-been-closed-exception/)

## possible fix
`schemacrawler.crawl.TableExtRetriever#retrieveViewInformation` read `results.getString("VIEW_DEFINITION")` first.

### How to Reproduce

- version 16.17.4
- Oracle db
- `System.setProperty("SC_EXPERIMENTAL", "true")`
- retrieveViewInformation

### Relevant log output

```shell
WARNING: Could not read string value for column <VIEW_DEFINITION>
java.sql.SQLException: Stream has already been closed
	at oracle.jdbc.driver.LongAccessor.getBytesInternal(LongAccessor.java:131)
	at oracle.jdbc.driver.Accessor.getBytes(Accessor.java:963)
	at oracle.jdbc.driver.LongAccessor.getString(LongAccessor.java:158)
	at oracle.jdbc.driver.GeneratedStatement.getString(GeneratedStatement.java:227)
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:405)
	at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:657)
	at schemacrawler.crawl.MetadataResultSet.getString(MetadataResultSet.java:357)
	at schemacrawler.crawl.TableExtRetriever.retrieveViewInformation(TableExtRetriever.java:429)
	at us.fatehi.utility.scheduler.TaskDefinition.run(TaskDefinition.java:81)
	at us.fatehi.utility.scheduler.TimedTask.run(TimedTask.java:57)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### SchemaCrawler Version

16.17.4

### Java Version

8

### Operating System and Version

macos 12.5.1

### Relational Database System and Version

Oracle 19c

### JDBC Driver and Version

com.oracle.database.jdbc.debug:ojdbc8_g:21.6.0.0.1

**Comment by sualeh** [comment]
@ltxlouis - thanks for trying out the experimental feature, and reporting this issue with helpful information on how to fix. I will take a look, and fix it. I am working on the next half of this experimental feature, which is to use a database connection per thread. Once I get it working, I will see if I can release it as an early release, if you would like to try it out.
