### ISSUE TITLE
Hive does not support DatabaseMetaData.getURL()

### ISSUE THREAD

**Issue by paladin235** [schemacrawler/SchemaCrawler#910]
### Description

Starting with this commit [3cc7b37e5](https://github.com/schemacrawler/SchemaCrawler/blob/3cc7b37e58a83f271dbb7813e6f12fe549054d02/schemacrawler-api/src/main/java/schemacrawler/crawl/ConnectionInfoBuilder.java#L62-L62), SchemaCrawler fails to crawl Hive database systems because Hive does not support the `DatabaseMetaData.getURL()` call. Previously, this call was only executed to obtain additional information, and any failures were caught by a try/catch block.

### How to Reproduce

Try to crawl against a Hive 3.x database with SchemaCrawler 16.15.8 or higher. It should fail with a stack trace like below.

### Relevant log output

```shell
Caused by: java.sql.SQLFeatureNotSupportedException: Method not supported
	at org.apache.hive.jdbc.HiveDatabaseMetaData.getURL(HiveDatabaseMetaData.java:834)
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getURL(HikariProxyDatabaseMetaData.java)
	at schemacrawler.crawl.ConnectionInfoBuilder.build(ConnectionInfoBuilder.java:75)
	at schemacrawler.crawl.RetrieverConnection.<init>(RetrieverConnection.java:71)
	at schemacrawler.crawl.SchemaCrawler.<init>(SchemaCrawler.java:122)
	... 101 more
```
```


### SchemaCrawler Version

16.15.8+

### Java Version

11 and 17

### Operating System and Version

MacOS and Linux

### Relational Database System and Version

Hive 3.1.2

### JDBC Driver and Version

org.apache.hive:hive-jdbc:3.1.3

**Comment by paladin235** [comment]
@sualeh Thanks for the quick fix!

**Comment by sualeh** [comment]
@paladin235 - please try SchemaCrawler v16.19.1
